class XpathConstants:
    '''
    Xpath Constants
    '''

    NODE_TABLE_XPATH = "//table[@class='table table-bordered responsiveTable']"
    ADD_BUTTON_XPATH = "//i[@class='fa fa-plus']"
    NODE_NAME_XPATH = "//input[@placeholder='name']"
    NAME_ERROR_XPATH = "//small[@for='node.name']"
    HOSTNAME_XPATH = "//input[@placeholder='FQDN or IP']"
    HOSTNAME_ERROR_XPATH = "//small[@for='node.hostname']"
    NODE_USERNAME_XPATH = "//input[@placeholder='Username']"
    NODE_USERNAME_ERROR_XPATH = "//small[@for='node.username']"
    NODE_PASSWORD_XPATH = "//input[@placeholder='Password']"
    NODE_PASSWORD_ERROR_XPATH = "//small[@for='node.password']"
    NODE_TYPE_XPATH = "//select[@id='node.nodeType']"
    NODE_TYPE_ERROR_XPATH = "//div[@for='node.nodeType']"
    NODE_PLATFORM_TYPE_XPATH = "//select[@id='node.platformType']"
    CONFIGURE_BUTTON_XPATH = "//button[normalize-space()='Configure']"
    ERROR_MESSAGE_POPUP_XPATH = "//button[@aria-label='Close']"
    CLOSE_WIZARD_XPATH = "//button[normalize-space()='Close']"
    CLOSE_MESSAGE_POPUP_XPATH = "//span[@aria-hidden='true']"
    REMOVE_BUTTON_XPATH = "(//button[@type='button'])[10]"
    CONFIRM_BUTTON_XPATH = "//button[normalize-space()='Confirm']"
    REFRESH_BUTTON_XPATH = "//button[@data-toggle='refresh']"
    NODE_XPATH = "//th[normalize-space()='{}']"
    NODE_CHECKBOX_XPATH = "//label[@for='chk-id-{}']"
    SITE_TABLE_XPATH = "//table[@id='sites']"
    SITE_NAME_XPATH = "//input[@id='configureSite.name']"
    SITE_NAME_ERROR_XPATH = "//small[@for='configureSite.name']"
    SITE_DESCRIPTION_XPATH = "//input[@id='configureSite.description']"
    SITE_DESCRIPTION_ERROR_XPATH = "//small[@for='configureSite.description']"
    SITE_TYPE_XPATH = "//select[@id='configureSite.siteType']"
    SITE_PLATFORM_TYPE_XPATH = "//select[@id='configureSite.platformDetails.platformType']"
    SITE_NODE_XPATH = "//select[@id='configureSite.node']"
    VCENTER_XPATH = "//input[@id='configureSite.platformDetails.hostname']"
    VCENTER_ERROR_XPATH = "//small[@for='configureSite.platformDetails.hostname']"
    SITE_VCENTER_USERNAME_XPATH = "//input[@id='configureSite.platformDetails.username']"
    SITE_VCENTER_USERNAME_ERROR_XPATH = "//small[@for='configureSite.platformDetails.username']"
    SITE_VCENTER_PASSWORD_XPATH = "//input[@id='configureSite.platformDetails.password']"
    SITE_VCENTER_PASSWORD_ERROR_XPATH = "//small[@for='configureSite.platformDetails.password']"
    SITE_AWS_REGION_XPATH = "//select[@id='configureSite.platformDetails.region']"
    SITE_AWS_ZONE_XPATH = "//select[@id='configureSite.platformDetails.availZone']"
    ACCESS_KEY_XPATH = "//input[@id='configureSite.platformDetails.accessKey']"
    SECRET_KEY_XPATH = "//input[@id='configureSite.platformDetails.secretKey']"
    CONFIGURE_SECTION_XPATH = "//span[normalize-space()='Configure']"
    NODE_SECTION_XPATH = "//span[normalize-space()='Nodes']"
    SITE_SECTION_XPATH = "//i[@class='fa fa-cloud']"
    SITE_XPATH = "//span[normalize-space()='{}']"
    SITE_URL_XPATH = "//a[normalize-space()='{}']"
    SITE_CHECKBOX_XPATH = "//label[@for='chk-id-{}-sites']"
    TABLE_XPATH = "//div[@class='col']//div[@class='card-body']"
    BOOT_DELAY_XPATH = "//input[@id='drplan.bootDelay']"
    NEXT_BUTTON_XPATH = "//button[normalize-space()='Next']"
    BACK_BUTTON_XPATH = "//button[normalize-space()='Back']"
    REPLICATION_MINUTE_INTERVAL_XPATH = "//select[@id='replication-interval-minute']"
    ENCRYPTION_ON_WIRE_CHECKBOX_XPATH = "//label[@for='drplan.isEncryptionOnWire']"
    FINISH_BUTTON_XPATH = "//button[normalize-space()='Finish']"
    PROTECTION_PLAN_NAME_TEXTBOX_XPATH = "//input[@id='drplan.name']"
    PROTECTION_SITE_NAME_XPATH = "//select[@id='drplan.protectedSite']"
    RECOVERY_SITE_NAME = "//select[@id='drplan.recoverySite']"
    SEARCH_BOX_XPATH = "//input[@id='planvmstep']"
    ARROW_BUTTON_XPATH = "//div[@class='d-flex flex-row-reverse col-sm-6']//div[@class='wizard-header-options']"
    VIRTUAL_MACHINE_NAME_XPATH = "//a[@id='dm-accordion-{}']"
    GENERAL_TAB_XPATH = "//span[@id='{}-General']"
    LOCATION_FOLDER_PATH_XAPTH = "//a[@id='{}-vmConfig.general.folderPath']"
    LOCATION_FOLDER_PATH_CHECKBOX_XPATH = "//input[@id='{}-vmConfig.general.folderPath-{}']"
    OK_BUTTON_XPATH = "//button[normalize-space()='Ok']"
    GUEST_OS_XPATH = "//select[@id='{}-vmConfig.general.guestOS']"
    FIRMAWARE_TYPE_XPATH = "//select[@id='{}-vmConfig.general.firmwareType']"
    COMPUTE_XPATH = "//input[@id='{}-vmConfig.general.hostMoref']"
    STORAGE_XPATH = "//input[@id='{}-vmConfig.general.dataStoreMoref']"
    CPU_XPATH = "//input[@id='{}-vmConfig.general.numcpu']"
    NETWORK_TAB_XPATH = "//span[@id='{}-Network']"
    CONFIG_XPATH = "//a[@id='{}-vmConfig.network.net1-index-{}']"
    NETWORK_TEXTBOX_XPATH = "//input[@id='{}-vmConfig.network.net1-eth-{}-network']"
    ADAPTER_TYPE_TEXTBOX_XPATH = "//select[@id='{}-vmConfig.network.net1-eth-{}-adapterType']"
    SAVE_BUTTON_XPATH = "//button[@class='btn btn-success']"
    PROTECTION_PLAN_SECTION_XPATH = "//span[normalize-space()='Protection Plans']"
    VM_CHECKBOX_XPATH = "//p[.='{}']"
    AWS_VM_CHECKBOX_XPATH = "//label[@for='chk-moref-0']"
    # VMWARE_VM_CHECKBOX_XPATH = "//label[@for='ui.site.vmware.selectedvms-{}']"
    DATACENTER_ARROW_BUTTON = "//box-icon[@id='{}']"
    VIRTUAL_MACHINE_ICON_XPATH = "//label[normalize-space()='Virtual Machines']"
    JOBS_SECTION_XPATH = "//span[normalize-space()='Jobs']"
    REPLICATION_SECTION_XPATH = "//span[normalize-space()='Replication']"
    USERNAME_TEXTBOX_XPATH = "//input[@placeholder='Enter username']"
    PASSWORD_TEXTBOX_XPATH = "//input[@placeholder='Enter password']"
    TEST_RECOVERY_VM_CHECKBOX_XPATH = "//label[@for='chk-moref-0-recoveryvms']"
    VM_LIST_TABLE_XPATH = "//table[@class='table table-bordered responsiveTable']"
    PROTECTION_PLAN_XPATH = "//a[normalize-space()='{}']"
    ACTIONS_BUTTON_XPATH = "//button[@class='btn btn-secondary']"
    TEST_RECOVRY_BUTTON_XPATH = "//i[@class='fa fa-check']"
    RECOVERY_SECTION_XPATH = "//i[@class='fas fa-undo']"
    RECOVERY_TABLE_ITEM_XPATH = "//th[@class='itemRendererContainer']"
    RECOVERY_BUTTON_XPATH = "//i[@id='recover']"
    TEST_RECOVERY_WORKLOAD_XPATH = "//label[normalize-space()='Select workloads for Test Recovery.']"
    RECOVERY_WORKLOAD_XPATH = "//label[normalize-space()='Select workloads for Recovery.']"
    MIGRATE_BUTTON_XPATH = "//i[@class='fa fa-clone']"
    AUTO_MIGRATION_CHECKBOX_XPATH = "//div[@class='col-sm-8']//div[@class='col-sm-1']"
    VIRTUAL_MACHINE_SECTION_XPATH = "//span[normalize-space()='Virtual Machines']"
    ENCRYPTION_KMS_KEY_XPATH = "//select[@class='form-control form-control-sm custom-select ""form-control']"
    REVERSE_BUTTON_XPATH = "//i[@class='fa fa-backward']"
    NETWORK_XPATH = "//span[@aria-hidden='true'][.='Network']"
    CONFIG = "//a[@href='#'][.='Config']"
    REVERSE_SUFFIX_XPATH = "//input[@id='reverse.suffix']"
    GENERAL_TAB = "//span[@aria-hidden='true'][.='General']"
    KMS_KEY = "//select[@class='form-control form-control-sm custom-select form-control']"
    CLEANUP_BUTTON_XPATH = "//i[@class='fa fa-broom']"
    INSTANCE_TYPE_XPATH = "//input[@id='{}-vmConfig.general.instanceType']"
    VOLUME_TYPE_XPATH = "//select[@id='{}-vmConfig.general.volumeType']"
    VPC_XPATH = "//select[@id='{}-vmConfig.network.net1-eth-{}-vpcId']"
    SUBNET_XPATH = "//select[@id='{}-vmConfig.network.net1-eth-{}-subnet']"
    PRIVATE_IP_XPATH = "//input[@id='{}-vmConfig.network.net1-eth-{}-privateIP']"
    SECURITY_GROUP_XPATH = "//select[@id='{}-vmConfig.network.net1-eth-{}-securityGroups']"
    NETWORK_SAVE_BUTTON = "//button[@id='{}-vmConfig.network.net1-eth-{}-save']"
    PROJECT_ID_XPATH = "//input[@id='configureSite.platformDetails.projectId']"
    STORAGE_ACCOUNT_XPATH = "//input[@id='configureSite.platformDetails.storageAccount']"
    TENANT_ID_XPATH = "//input[@id='configureSite.platformDetails.tenantId']"
    CLIENT_ID_XPATH = "//input[@id='configureSite.platformDetails.clientId']"
    RESOURCE_GROUP_XPATH = "//input[@id='{}-vmConfig.general.folderPath']"
    AVAILABILITY_ZONE_XPATH = "//select[@id='{}-vmConfig.general.availibility.zone']"
    VM_SIZE_XPATH = "//div[@id='{}-vmConfig.general.instanceType']"
    SEARCH_SECURITY_GROUP_XPATH = "//input[@id='{}-vmConfig.network.net1-eth-{}-securityGroups']"
    PUBLIC_IP_XPATH = "//select[@id='{}-vmConfig.network.net1-eth-{}-publicIP']"
    RECOVERY_CONFIGURATION_XPATH = "//label[normalize-space()='Recovery Configuration']"
    AUTO_PUBLIC_IP_CHECKBOX = "//input[@id='{}-vmConfig.network.net1-eth-{}-isPublic']"
    MONITOR_SECTION_XPATH = "//i[@class='fa fa-chart-bar fa-s-lg']"
    EVENT_SECTION_XAPTH = "//i[@class='bx bxs-calendar-event']"
    REPLICATION_JOBS_XPATH = "//span[normalize-space()='Replication Jobs']"
    RECOVERY_JOBS_XPATH = "//span[normalize-space()='Recovery Jobs']"
    UI_PASSWORD_TEXTBOX_XPATH = "//input[@id='password']"
    LOGIN_BUTTON_XPATH = "//button[normalize-space()='Log In']"
    APPLY_TO_OTHER_VM_BUTTON_XPATH = "//a[normalize-space()='Apply to other virtual machines']"
    SELECT_VIRTUAL_MACHINE_DROPDOWN_XPATH = "//input[@id='react-select-20-input']"
    SELECT_CONFIGURATION_DROPDOWN_XPATH = "//input[@id='react-select-21-input']"
    STOP_BUTTON_XPATH = "//button[contains(.,'Stop')]"
    MESSAGE_POPUP_XPATH = "//div[@role='alert']"
    MODAL_CONTENT_XPATH = "//div[@class='modal-content']"
    PROTECTION_PLAN_DATA_XPATH = "//div[@class='padding-top-20 row']"
    VIRTUAL_MACHINE_TABLE_XPATH = "//div[@class='col-sm-12']//div[@class='container-fluid']//table[@class='table table-bordered responsiveTable']"
    LOADER_XPATH = "//div[@class='ripple__box']"
    EVENTS_TABLE_XPATH = "//table[@id='events']"
    EDIT_XPATH = "//i[@class='fa fa-edit']"
    NODE_OFFLINE_BUTTON_XPATH = "//i[@class='fas fa-power-off']"
    NODE_ONLINE_BUTTON_XPATH = "//i[@class='fas fa-plug']"
    EDIT_BUTTON_XPATH = "//button[contains(.,'Edit')]"
    CLOSE_ICON_XPATH = "//box-icon[@name='x-circle']"
    REMOVE_XPATH = "//button[contains(.,'Remove')]"
    PROTECTION_PLAN_RUNNING_XPATH = "//span[normalize-space()='Running']"
    PROTECTION_PLAN_STOP_XPATH = "//span[normalize-space()='Stopped']"
    PROTECTION_PLAN_ELEMENT_XPATH = "//a[contains(text(),'Protection Plans')]"
    DISKS_JOBS_ICON_XPATH = "//input[@id='disks-options']"
    START_BUTTON_XPATH = "//button[contains(.,'Start')]"
    RECOVERY_SITE_OPERATIONS_SEARCH_BOX_XPATH = "//input[@id='recoverymachine']"
    EVENT_SEARCH_BOX_XPATH = "//input[@id='datableSearch']"
    PROTECTED_MACHINE_SEARCH_BOX = "//input[@id='protectedmachine']"
    SETTINGS_SECTION_XPATH = "//i[@class='fas fa-sliders-h']"
    EMAIL_SECTION = "//span[normalize-space()='Email']"
    CONFIGURE_NOW_BUTTON_XPATH = "//button[@class='btn btn-secondary btn-sm margin-right-2']"
    EMAIL_ADDRESS_XPATH = "//input[@id='emailConfiguration.emailAddress']"
    EMAIL_PASSWORD = "//input[@id='emailConfiguration.password']"
    SMTP_HOST = "//input[@id='emailConfiguration.smtpHost']"
    SMTP_PORT = "//input[@id='emailConfiguration.smtpPort']"
    SUBSCRIBED_EVENTS = "//select[@id='emailRecipient.subscribedEvents']"
    RECIPIENT_EMAIL_ADDRESS = "//input[@id='emailRecipient.emailAddress']"
    TECH_SUPPORT_XPATH = "//i[@class='fas fa-headset']"
    DESCRIPTION_INPUT_TEXTBOX = "//textarea[@id='description-input']"
    GENERATE_BUNDLE_BUTTON_XPATH = "//button[normalize-space()='Generate Bundle']"
    PROTECTED_MACHINE_XPATH = "//label[normalize-space()='Protected Machines']"
    DROPDOWN_XPATH = "//option[@value='{}']"