class XpathConstants:
    """Xpath"""

    NODE_TABLE_XPATH = "//table[@class='table table-bordered responsiveTable']"
    ADD_BUTTON_XPATH = "//i[@class='fa fa-plus']"
    NODE_NAME_XPATH = "//input[@placeholder='name']"
    NAME_ERROR_XPATH = "//small[@for='node.name']"
    HOSTNAME_XPATH = "//input[@placeholder='FQDN or IP']"
    HOSTNAME_ERROR_XPATH = "//small[@for='node.hostname']"
    NODE_USERNAME_XPATH = "//input[@placeholder='Username']"
    NODE_USERNAME_ERROR_XPATH = "//small[@for='node.username']"
    NODE_PASSWORD_XPATH = "//input[@placeholder='Password']"
    NODE_PASSWORD_ERROR_XPATH = "//small[@for='node.password']"
    NODE_TYPE_XPATH = "//select[@id='node.nodeType']"
    NODE_TYPE_ERROR_XPATH = "//div[@for='node.nodeType']"
    NODE_PLATFORM_TYPE_XPATH = "//select[@id='node.platformType']"
    CONFIGURE_BUTTON_XPATH = "//button[normalize-space()='Configure']"
    ERROR_MESSAGE_POPUP_XPATH = "//button[@aria-label='Close']"
    CLOSE_WIZARD_XPATH = "//button[normalize-space()='Close']"
    SUCCESS_MESSAGE_POPUP_XPATH = "//span[@aria-hidden='true']"
    REMOVE_BUTTON_XPATH = "(//button[@type='button'])[10]"
    CONFIRM_BUTTON_XPATH = "//button[normalize-space()='Confirm']"
    REFRESH_BUTTON_XPATH = "//button[@data-toggle='refresh']"
    NODE_XPATH = "//th[normalize-space()='{}']"
    NODE_CHECKBOX_XPATH = "//label[@for='chk-id-{}']"
    SITE_TABLE_XPATH = "//table[@id='sites']"
    SITE_NAME_XPATH = "//input[@id='configureSite.name']"
    SITE_NAME_ERROR_XPATH = "//small[@for='configureSite.name']"
    SITE_DESCRIPTION_XPATH = "//input[@id='configureSite.description']"
    SITE_DESCRIPTION_ERROR_XPATH = "//small[@for='configureSite.description']"
    SITE_TYPE_XPATH = "//select[@id='configureSite.siteType']"
    SITE_PLATFORM_TYPE_XPATH = "//select[@id='configureSite.platformDetails.platformType']"
    SITE_NODE_XPATH = "//select[@id='configureSite.node']"
    VCENTER_XPATH = "//input[@id='configureSite.platformDetails.hostname']"
    VCENTER_ERROR_XPATH = "//small[@for='configureSite.platformDetails.hostname']"
    SITE_VCENTER_USERNAME_XPATH = "//input[@id='configureSite.platformDetails.username']"
    SITE_VCENTER_USERNAME_ERROR_XPATH = "//small[@for='configureSite.platformDetails.username']"
    SITE_VCENTER_PASSWORD_XPATH = "//input[@id='configureSite.platformDetails.password']"
    SITE_VCENTER_PASSWORD_ERROR_XPATH = "//small[@for='configureSite.platformDetails.password']"
    SITE_AWS_REGION_XPATH = "//select[@id='configureSite.platformDetails.region']"
    SITE_AWS_ZONE_XPATH = "//select[@id='configureSite.platformDetails.availZone']"
    ACCESS_KEY_XPATH = "//input[@id='configureSite.platformDetails.accessKey']"
    SECRET_KEY_XPATH = "//input[@id='configureSite.platformDetails.secretKey']"
    CONFIGURE_SECTION_XPATH = "//span[normalize-space()='Configure']"
    NODE_SECTION_XPATH = "//span[normalize-space()='Nodes']"
    SITE_SECTION_XPATH = "//i[@class='fa fa-cloud']"
    SITE_XPATH = "//span[normalize-space()='{}']"
    SITE_URL_XPATH = "//a[normalize-space()='{}']"
    SITE_CHECKBOX_XPATH = "//label[@for='chk-id-{}-sites']"
    TABLE_XPATH = "//div[@class='col']//div[@class='card-body']"
    BOOT_DELAY_XPATH = "//input[@id='drplan.bootDelay']"
    NEXT_BUTTON_XPATH = "//button[normalize-space()='Next']"
    BACK_BUTTON_XPATH = "//button[normalize-space()='Back']"
    REPLICATION_MINUTE_INTERVAL_XPATH = "//select[@id='replication-interval-minute']"
    ENCRYPTION_ON_WIRE_CHECKBOX_XPATH = "//label[@for='drplan.isEncryptionOnWire']"
    FINISH_BUTTON_XPATH = "//button[normalize-space()='Finish']"
    PROTECTION_PLAN_NAME_TEXTBOX_XPATH = "//input[@id='drplan.name']"
    PROTECTION_SITE_NAME_XPATH = "//select[@id='drplan.protectedSite']"
    RECOVERY_SITE_NAME = "//select[@id='drplan.recoverySite']"
    SEARCH_BOX_XPATH = "//input[@id='datableSearch']"
    ARROW_BUTTON_XPATH = "(//box-icon[@name='chevron-down'])[1]"
    VIRTUAL_MACHINE_NAME_XPATH = "//a[@id='dm-accordion-{}']"
    GENERAL_TAB_XPATH = "//span[@id='{}-General']"
    LOCATION_FOLDER_PATH_XAPTH = "//a[@id='{}-vmConfig.general.folderPath']"
    LOCATION_FOLDER_PATH_CHECKBOX_XPATH = "//input[@id='{}-vmConfig.general.folderPath-{}']"
    OK_BUTTON_XPATH = "//button[normalize-space()='ok']"
    GUEST_OS_XPATH = "//select[@id='{}-vmConfig.general.guestOS']"
    FIRMAWARE_TYPE_XPATH = "//select[@id='{}-vmConfig.general.firmwareType']"
    COMPUTE_XPATH = "//input[@id='{}-vmConfig.general.hostMoref']"
    STORAGE_XPATH = "//input[@id='{}-vmConfig.general.dataStoreMoref']"
    CPU_XPATH = "//input[@id='{}-vmConfig.general.numcpu']"
    NETWORK_TAB_XPATH = "//span[@id='{}-Network']"
    CONFIG_XPATH = "//a[@id='{}-vmConfig.network.net1-index-{}']"
    NETWORK_TEXTBOX_XPATH = "//input[@id='{}-vmConfig.network.net1-eth-{}-network']"
    ADAPTER_TYPE_TEXTBOX_XPATH = "//select[@id='{}-vmConfig.network.net1-eth-{}-adapterType']"
    SAVE_BUTTON_XPATH = "//button[@class='btn btn-success']"
    PROTECTION_PLAN_SECTION_XPATH = "//span[normalize-space()='Protection Plans']"
    AWS_VM_CHECKBOX_XPATH = "//input[@id='chk-moref-0']"
    VMWARE_VM_CHECKBOX_XPATH = "//input[@id='ui.site.vmware.selectedvms-{}']"
    DATACENTER_ARROW_BUTTON = "//box-icon[@id='{}']"
    VIRTUAL_MACHINE_ICON_XPATH = "//label[normalize-space()='Virtual Machines']"
    JOBS_SECTION_XPATH = "//span[normalize-space()='Jobs']"
    REPLICATION_SECTION_XPATH = "//span[normalize-space()='Replication']"
    USERNAME_TEXTBOX_XPATH = "//input[@placeholder='Enter username']"
    PASSWORD_TEXTBOX_XPATH = "//input[@placeholder='Enter password']"
    TEST_RECOVERY_VM_CHECKBOX_XPATH = "//label[@for='chk-moref-0-recoveryvms']"
    REPLICATION_VM_LIST_TABLE_XPATH = "//table[@class='table table-bordered responsiveTable']"
    PROTECTION_PLAN_XPATH = "//a[normalize-space()='{}']"
    ACTIONS_BUTTON_XPATH = "//span[@class='d-none d-xl-inline-block ml-2 mr-1']"
    TEST_RECOVRY_BUTTON_XPATH = "//i[@id='TestRecovery']"
    RECOVERY_SECTION_XPATH = "//i[@class='fas fa-undo']"
    RECOVERY_TABLE_ITEM_XPATH = "//th[@class='itemRendererContainer']"
    RECOVERY_BUTTON_XPATH = "//i[@id='recover']"
    TEST_RECOVERY_WORKLOAD_XPATH = "//label[normalize-space()='Select workloads for Test Recovery.']"
    RECOVERY_WORKLOAD_XPATH = "//label[normalize-space()='Select workloads for Recovery.']"
    MIGRATE_BUTTON_XPATH = "//i[@id='Migrate']"
    AUTO_MIGRATION_CHECKBOX_XPATH = "//div[@class='col-sm-8']//div[@class='col-sm-1']"
    VIRTUAL_MACHINE_SECTION_XPATH = "//span[normalize-space()='Virtual Machines']"
    ENCRYPTION_KMS_KEY_XPATH = "//select[@class='form-control form-control-sm custom-select ""form-control']"
    REVERSE_BUTTON_XPATH = "//i[@id='Reverse']"
    NETWORK_XPATH = "//span[@aria-hidden='true'][.='Network']"
    CONFIG = "//a[@href='#'][.='Config']"
    SUBNET_XPATH = "//select[contains(.,'172.31.0.0/20 - subnet-7a8d2e1c')]"
    PRIVATE_IP_XPATH = "//input[@placeholder='Assign New']"
    VPC_XPATH = "//select[@class='form-control form-control-sm custom-select ""form-control'][contains(.,'10.254.239.0/24,20.254.239.0/24')]"
    REVERSE_SUFFIX_XPATH = "//input[@id='reverse.suffix']"
    GENERAL_TAB = "//span[@aria-hidden='true'][.='General']"
    KMS_KEY = "//select[@class='form-control form-control-sm custom-select form-control']"
    CLEANUP_BUTTON_XPATH = "//i[@id='CleanupTestRecoveries']"








